# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='URL',
            new_name='GrupoURL',
        ),
    ]
