#!/bin/bash
PYTHONPATH=$OPENSHIFT_REPO_DIR/b2card
django-admin.py migrate --settings='b2card.production' --pythonpath=$PYTHONPATH
python $PYTHONPATH/manage.py collectstatic -c --noinput --settings='b2card.production' --pythonpath=$PYTHONPATH
python $PYTHONPATH/manage.py createsuperuser --username moises --email moises@b2card.com.br --noinput --settings='b2card.production' --pythonpath=$PYTHONPATH
