# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=19)),
                ('endereco', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=10)),
                ('dias_faturamento', models.IntegerField(default=None)),
                ('dias_pagamento', models.IntegerField(default=None)),
                ('data_contratacao', models.DateField(blank=True, default=None)),
                ('data_rescisao', models.DateField(default=None, null=True)),
                ('centro_custo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.CentroCusto')),
            ],
        ),
    ]
