# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoValorHora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_hora', models.CharField(max_length=30)),
                ('valor_hora', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_contratacao',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_rescisao',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='tipovalorhora',
            name='cliente',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente'),
        ),
    ]
