# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20161101_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='data_rescisao',
            field=models.DateField(default=None, null=True),
        ),
    ]
