# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20161101_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroResultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=19)),
                ('cliente', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
    ]
