# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_centroresultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dias_faturamento',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dias_pagamento',
            field=models.IntegerField(default=None),
        ),
    ]
