# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_auto_20161116_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='centroresultado',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='tipovalorhora',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='CentroResultado',
        ),
        migrations.DeleteModel(
            name='TipoValorHora',
        ),
    ]
