# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_valorhora_vigencia'),
        ('clientes', '0006_auto_20161123_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='centro_custo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.CentroCusto'),
        ),
    ]
