# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandas', '0001_initial'),
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('quantidade_horas', models.IntegerField()),
                ('valor_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor_parcela', models.FloatField(max_length=30, null=True)),
                ('status', models.CharField(choices=[('PE', 'Previsto'), ('PA', 'Pendente aprova\xe7\xe3o'), ('PF', 'Pendente faturamento'), ('FA', 'Faturado'), ('PA', 'Pago')], max_length=2, null=True)),
                ('data_previsto_parcela', models.DateField(null=True)),
                ('tipo_parcela', models.CharField(choices=[('P', 'Parcela'), ('M', 'Medi\xe7\xe3o')], max_length=1, null=True)),
                ('demanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelaFase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(max_length=30, null=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandas.OrcamentoFase')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faturamento.Parcela')),
            ],
        ),
        migrations.AddField(
            model_name='medicao',
            name='parcela_fase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faturamento.ParcelaFase'),
        ),
        migrations.AddField(
            model_name='medicao',
            name='valor_hora',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.ValorHora'),
        ),
    ]
