# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contasreceber',
            name='tipo_conta',
            field=models.CharField(choices=[('P', 'Parcela'), ('M', 'Medi\xe7\xe3o')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='status',
            field=models.CharField(choices=[('PE', 'Previsto'), ('PA', 'Pendente aprova\xe7\xe3o'), ('PF', 'Pendente faturamento'), ('FA', 'Faturado'), ('PA', 'Pago')], max_length=2, null=True),
        ),
    ]
