# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-22 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteFaturamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(default=None)),
                ('valor_total', models.FloatField(default=None)),
                ('total_horas', models.IntegerField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='parcela',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendente'), ('PA', 'Pendente aprovação'), ('PF', 'Pendente faturamento'), ('FA', 'Faturado'), ('PA', 'Pago')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='parcela',
            name='lote_faturamento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='faturamento.LoteFaturamento'),
        ),
    ]
