# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-28 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0002_auto_20161228_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicao',
            name='valor',
        ),
    ]
