# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0038_demanda_unidade_administrativa'),
        ('faturamento', '0002_auto_20161201_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contasreceber',
            name='demanda',
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='contas_receber',
        ),
        migrations.AddField(
            model_name='parcela',
            name='demanda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda'),
        ),
        migrations.DeleteModel(
            name='ContasReceber',
        ),
    ]
