# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0003_auto_20161201_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='numero_horas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='valor_parcela',
            field=models.FloatField(max_length=30, null=True),
        ),
    ]
