# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0003_lotefaturamento_pessoa_fisica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotefaturamento',
            name='total_horas',
            field=models.FloatField(default=None),
        ),
    ]
