# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0004_auto_20161201_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcela',
            name='numero_horas',
            field=models.FloatField(null=True),
        ),
    ]
