# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0005_auto_20170223_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcela',
            old_name='lote_faturamento',
            new_name='pacote_itens',
        ),
    ]
