# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_auto_20161129_1438'),
        ('faturamento', '0005_auto_20161201_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('quantidade_horas', models.IntegerField()),
                ('valor_total', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='parcela',
            name='numero_horas',
        ),
        migrations.AddField(
            model_name='parcela',
            name='tipo_parcela',
            field=models.CharField(choices=[('P', 'Parcela'), ('M', 'Medi\xe7\xe3o')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='medicao',
            name='parcela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faturamento.Parcela'),
        ),
        migrations.AddField(
            model_name='medicao',
            name='valor_hora',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.ValorHora'),
        ),
    ]
