# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_unidadeadministrativa_custo_operacao_hora'),
        ('faturamento', '0006_auto_20170223_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacoteitens',
            name='pessoa_fisica',
        ),
        migrations.AddField(
            model_name='pacoteitens',
            name='cliente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.PessoaJuridica'),
        ),
    ]
