# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0040_auto_20161205_1420'),
        ('faturamento', '0007_parcela_numero_horas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelaFase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandas.Fase')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faturamento.Parcela')),
            ],
        ),
        migrations.RemoveField(
            model_name='medicao',
            name='parcela',
        ),
        migrations.AddField(
            model_name='medicao',
            name='parcela_fase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faturamento.ParcelaFase'),
        ),
    ]
