# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0008_auto_20170223_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacoteitens',
            name='total_horas',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pacoteitens',
            name='valor_total',
            field=models.FloatField(default=None, null=True),
        ),
    ]
