# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-14 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0008_auto_20161213_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcela',
            name='numero_horas',
        ),
        migrations.AddField(
            model_name='parcelafase',
            name='valor',
            field=models.FloatField(max_length=30, null=True),
        ),
    ]
