# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0009_auto_20170223_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='data_aprovacao_faturamento',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='parcela',
            name='data_envio_aprovacao',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='parcela',
            name='data_faturamento',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='parcela',
            name='data_pagamento',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='parcela',
            name='data_previsto_pagamento',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='parcela',
            name='data_previsto_parcela',
            field=models.DateField(default=None, null=True),
        ),
    ]
