# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0011_auto_20170321_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdespesa',
            name='tipo_despesa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cadastros.TipoDespesa'),
        ),
    ]
