# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0012_auto_20170321_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotedespesa',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('E', 'Enviado'), ('A', 'Aceito'), ('R', 'Recusado'), ('D', 'Deletado')], default=None, max_length=2),
        ),
    ]
