# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0013_lotedespesa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotedespesa',
            name='valor_total',
            field=models.FloatField(default=None, null=True),
        ),
    ]
