# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0014_lotedespesa_valor_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotedespesa',
            name='motivo_despesa',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
