# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0017_fase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default=None, max_length=100)),
                ('data_inicio', models.DateField(default=None)),
                ('data_fim', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeProfissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_horas', models.IntegerField(default=None)),
                ('atividade', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demandas.Atividade')),
                ('pessoa_fisica', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.PessoaFisica')),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_demanda', models.CharField(default=None, max_length=30)),
                ('descricao', models.TextField(default=None, null=True)),
                ('status_demanda', models.CharField(choices=[(b'O', b'Em or\xc3\xa7amenta\xc3\xa7\xc3\xa3o'), (b'A', b'Aguardando aprova\xc3\xa7\xc3\xa3o'), (b'N', b'N\xc3\xa3o aprovada'), (b'C', b'Cancelada'), (b'H', b'Em homologa\xc3\xa7\xc3\xa3o'), (b'I', b'Implantada'), (b'D', b'Em desenvolvimento')], max_length=1, null=True)),
                ('codigo_demanda', models.CharField(max_length=12, null=True)),
                ('cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.PessoaJuridica')),
                ('unidade_administrativa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.UnidadeAdministrativa')),
            ],
        ),
        migrations.CreateModel(
            name='FaseAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('demanda', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda')),
                ('fase', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Fase')),
                ('responsavel', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.PessoaFisica')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_selecionado', models.FloatField()),
                ('quantidade_horas', models.IntegerField()),
                ('valor_total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField()),
                ('data_observacao', models.DateField()),
                ('demanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ocorrencia', models.CharField(choices=[(b'E', b'Erro'), (b'S', b'Erro de Especifica\xc3\xa7\xc3\xa3o'), (b'F', b'Fora do escopo inicial do projeto')], max_length=1)),
                ('descricao', models.CharField(max_length=100)),
                ('nome_solicitante', models.CharField(max_length=30)),
                ('data_solicitacao', models.DateField(null=True)),
                ('data_prevista_conclusao', models.DateField(null=True)),
                ('etapa', models.CharField(choices=[(b'C', b'Conclu\xc3\xaddo'), (b'A', b'Aguardando an\xc3\xa1lise'), (b'E', b'Em avalia\xc3\xa7\xc3\xa3o')], max_length=1)),
                ('descricao_motivo', models.TextField()),
                ('observacao', models.TextField()),
                ('demanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.PessoaFisica')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(default=None, null=True)),
                ('total_orcamento', models.FloatField(default=None, null=True)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda')),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default=None, max_length=100)),
                ('total_horas', models.IntegerField(default=None, null=True)),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Fase')),
                ('orcamento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demandas.Orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoFase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor_total', models.FloatField(default=None)),
                ('orcamento', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demandas.Orcamento')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.IntegerField(default=None, null=True)),
                ('orcamento_atividade', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demandas.OrcamentoAtividade')),
                ('perfil', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.ValorHora')),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recimento_solicitacao', models.DateField()),
                ('data_limite_entrega', models.DateField(null=True)),
                ('data_real_entrega', models.DateField(null=True)),
                ('numerdo_proposta', models.CharField(max_length=30, null=True)),
                ('data_aprovacao', models.DateField(null=True)),
                ('empresa_ganhadora', models.CharField(max_length=30, null=True)),
                ('total_horas_ganhadora', models.IntegerField(null=True)),
                ('demanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('analise_inicio', models.DateField(null=True)),
                ('analise_fim', models.DateField(null=True)),
                ('analise_fim_real', models.DateField(null=True)),
                ('densenvolvimento_inicio', models.DateField(null=True)),
                ('desenvolvimento_fim', models.DateField(null=True)),
                ('desenvolvimento_fim_real', models.DateField(null=True)),
                ('homologacao_possui_sit', models.CharField(choices=[(b'S', b'Sim'), (b'N', b'N\xc3\xa3o')], max_length=1, null=True)),
                ('homologacao_inicio', models.DateField(null=True)),
                ('homologacao_fim', models.DateField(null=True)),
                ('homologacao_fim_real', models.DateField(null=True)),
                ('forecast', models.CharField(max_length=30, null=True)),
                ('aceite', models.CharField(choices=[(b'S', b'Sim'), (b'N', b'N\xc3\xa3o')], max_length=1, null=True)),
                ('evidencias', models.CharField(max_length=30, null=True)),
                ('implantacao_producao', models.DateField(null=True)),
                ('implantacao_in_loco', models.CharField(choices=[(b'S', b'Sim'), (b'N', b'N\xc3\xa3o')], max_length=1, null=True)),
                ('analista_tecnico_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandas_tarefa_related', related_query_name='demandas_tarefas', to='cadastros.PessoaFisica')),
                ('demanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.PessoaFisica')),
            ],
        ),
        migrations.AddField(
            model_name='itemfase',
            name='fase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demandas.OrcamentoFase'),
        ),
        migrations.AddField(
            model_name='itemfase',
            name='valor_hora',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.ValorHora'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='fase_atividade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demandas.FaseAtividade'),
        ),
    ]
