# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('cadastros', '0001_initial'),
        ('recursos', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('horas_previstas', models.IntegerField()),
                ('centro_resultado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.CentroResultado')),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_demanda', models.CharField(default=None, max_length=30)),
                ('descricao', models.TextField(default=None, null=True)),
                ('status_demanda', models.CharField(choices=[(b'O', b'Em or\xc3\xa7amenta\xc3\xa7\xc3\xa3o'), (b'A', b'Aguardando aprova\xc3\xa7\xc3\xa3o'), (b'N', b'N\xc3\xa3o aprovada'), (b'C', b'Cancelada'), (b'H', b'Em homologa\xc3\xa7\xc3\xa3o'), (b'I', b'Implantada'), (b'D', b'Em desenvolvimento')], max_length=1, null=True)),
                ('codigo_demanda', models.CharField(max_length=12, null=True)),
                ('tipo_parcela', models.CharField(choices=[(b'P', b'Parcela'), (b'M', b'Medi\xc3\xa7\xc3\xa3o')], max_length=1, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
                ('unidade_administrativa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.UnidadeAdministrativa')),
            ],
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor_total', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='FaturamentoDemanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('numero_nota', models.CharField(default=None, max_length=30)),
                ('valor_total_faturamento', models.CharField(max_length=30, null=True)),
                ('status', models.CharField(choices=[(b'P', b'Pendente'), (b'A', b'Aprovado'), (b'R', b'Reprovado')], max_length=1, null=True)),
                ('data_envio_aprovacao', models.DateField(null=True)),
                ('data_previsto_faturamento', models.DateField(null=True)),
                ('data_previsto_pagamento', models.DateField(null=True)),
                ('data_pagamento', models.DateField(null=True)),
                ('data_fatura', models.DateField(null=True)),
                ('demanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_selecionado', models.FloatField()),
                ('quantidade_horas', models.IntegerField()),
                ('valor_total', models.FloatField()),
                ('fase', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demandas.Fase')),
                ('valor_hora', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.ValorHora')),
            ],
        ),
        migrations.CreateModel(
            name='Observacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField()),
                ('data_observacao', models.DateField()),
                ('demanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ocorrencia', models.CharField(choices=[(b'E', b'Erro'), (b'S', b'Erro de Especifica\xc3\xa7\xc3\xa3o'), (b'F', b'Fora do escopo inicial do projeto')], max_length=1)),
                ('descricao', models.CharField(max_length=100)),
                ('nome_solicitante', models.CharField(max_length=30)),
                ('data_solicitacao', models.DateField(null=True)),
                ('data_prevista_conclusao', models.DateField(null=True)),
                ('etapa', models.CharField(choices=[(b'C', b'Conclu\xc3\xaddo'), (b'A', b'Aguardando an\xc3\xa1lise'), (b'E', b'Em avalia\xc3\xa7\xc3\xa3o')], max_length=1)),
                ('descricao_motivo', models.TextField()),
                ('observacao', models.TextField()),
                ('demanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(default=None, null=True)),
                ('total_orcamento', models.FloatField(default=None, null=True)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda')),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recimento_solicitacao', models.DateField()),
                ('data_limite_entrega', models.DateField(null=True)),
                ('data_real_entrega', models.DateField(null=True)),
                ('numerdo_proposta', models.CharField(max_length=30, null=True)),
                ('data_aprovacao', models.DateField(null=True)),
                ('empresa_ganhadora', models.CharField(max_length=30, null=True)),
                ('total_horas_ganhadora', models.IntegerField(null=True)),
                ('demanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('analise_inicio', models.DateField(null=True)),
                ('analise_fim', models.DateField(null=True)),
                ('analise_fim_real', models.DateField(null=True)),
                ('densenvolvimento_inicio', models.DateField(null=True)),
                ('desenvolvimento_fim', models.DateField(null=True)),
                ('desenvolvimento_fim_real', models.DateField(null=True)),
                ('homologacao_possui_sit', models.CharField(choices=[(b'S', b'Sim'), (b'N', b'N\xc3\xa3o')], max_length=1, null=True)),
                ('homologacao_inicio', models.DateField(null=True)),
                ('homologacao_fim', models.DateField(null=True)),
                ('homologacao_fim_real', models.DateField(null=True)),
                ('forecast', models.CharField(max_length=30, null=True)),
                ('aceite', models.CharField(choices=[(b'S', b'Sim'), (b'N', b'N\xc3\xa3o')], max_length=1, null=True)),
                ('evidencias', models.CharField(max_length=30, null=True)),
                ('implantacao_producao', models.DateField(null=True)),
                ('implantacao_in_loco', models.CharField(choices=[(b'S', b'Sim'), (b'N', b'N\xc3\xa3o')], max_length=1, null=True)),
                ('analista_tecnico_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandas_tarefa_related', related_query_name='demandas_tarefas', to='recursos.Funcionario')),
                ('demanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='ValorHoraFaturamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(null=True)),
                ('quantidade_horas', models.IntegerField(null=True)),
                ('valor_faturamento', models.CharField(max_length=30, null=True)),
                ('faturamento_demanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.FaturamentoDemanda')),
                ('valor_hora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.ValorHora')),
            ],
        ),
        migrations.AddField(
            model_name='fase',
            name='orcamento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demandas.Orcamento'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='demanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='responsavel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recursos.Funcionario'),
        ),
    ]
