# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='data_orcamento',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='unidade_administrativa',
        ),
        migrations.AddField(
            model_name='demanda',
            name='unidade_administrativa',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='propostas',
            name='data_proposta',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='propostas',
            name='orcamento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demandas.Orcamento'),
        ),
    ]
