# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_naturezademanda'),
        ('demandas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='analista_tecnico_responsavel',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='demanda',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='demanda',
            name='analista_tecnico_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandas_demanda_related', related_query_name='demandas_demandas', to='cadastros.PessoaFisica'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='natureza_demanda',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.NaturezaDemanda'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.PessoaFisica'),
        ),
        migrations.AddField(
            model_name='demanda',
            name='responsavel_cliente',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='tipo_demanda',
            field=models.CharField(choices=[(b'E', b'Externo'), (b'I', b'Interno')], default=None, max_length=1),
        ),
        migrations.DeleteModel(
            name='Tarefa',
        ),
    ]
