# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-28 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='tipo_parcela',
        ),
    ]
