# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0002_auto_20170123_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlocacaoHoras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas_alocadas', models.DateTimeField(default=None)),
                ('percentual_concluido', models.IntegerField()),
                ('observacao', models.TextField(default=None, null=True)),
                ('data_alocacao', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='atividadeprofissional',
            name='horas_alocadas',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='atividadeprofissional',
            name='percentual_concluido',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='alocacaohoras',
            name='atividade_profissional',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='demandas.AtividadeProfissional'),
        ),
    ]
