# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_fase'),
        ('demandas', '0002_remove_demanda_tipo_parcela'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_horas', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilAtividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.IntegerField(default=None)),
                ('orcamento_atividade', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demandas.OrcamentoAtividade')),
                ('perfil', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.ValorHora')),
            ],
        ),
        migrations.RenameModel(
            old_name='Fase',
            new_name='OrcamentoFase',
        ),
        migrations.AddField(
            model_name='orcamentoatividade',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.Fase'),
        ),
        migrations.AddField(
            model_name='orcamentoatividade',
            name='orcamento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demandas.Orcamento'),
        ),
    ]
