# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20161101_1251'),
        ('demandas', '0002_auto_20161028_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaturamentoDemanda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
                ('data', models.DateField()),
                ('valor_hora', models.CharField(max_length=10)),
                ('quantidade_horas', models.IntegerField()),
                ('valor_faturamento', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Reprovado')], max_length=1)),
                ('data_envio_aprovacao', models.DateField()),
                ('data_aprovacao_fatura', models.DateField()),
                ('data_fatura', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='atividades',
            name='demanda',
        ),
        migrations.RemoveField(
            model_name='atividades',
            name='responsavel',
        ),
        migrations.DeleteModel(
            name='DespesasExtras',
        ),
        migrations.RemoveField(
            model_name='propostas',
            name='demanda',
        ),
        migrations.RemoveField(
            model_name='propostas',
            name='orcamento',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='coordenador',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='descricao_cliente',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='identificacao_cliente',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='informacoes_nfe',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='nomde_documento_resumido',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='numero_demanda',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='unidade_administrativa',
        ),
        migrations.AddField(
            model_name='demanda',
            name='data_aprovacao',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='demanda',
            name='descricao',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='demanda',
            name='identificacao',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='demanda',
            name='numero_proposta',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.DeleteModel(
            name='Atividades',
        ),
        migrations.DeleteModel(
            name='Orcamento',
        ),
        migrations.DeleteModel(
            name='Propostas',
        ),
        migrations.AddField(
            model_name='faturamentodemanda',
            name='demanda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda'),
        ),
        migrations.AddField(
            model_name='faturamentodemanda',
            name='tipo_horas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.TipoValorHora'),
        ),
    ]
