# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0003_auto_20170112_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoatividade',
            name='descricao',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
