# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0003_auto_20170124_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alocacaohoras',
            name='data_alocacao',
        ),
        migrations.AddField(
            model_name='alocacaohoras',
            name='data_alocacao_milisegundos',
            field=models.IntegerField(default=None),
        ),
    ]
