# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-04 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0004_auto_20161103_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamentodemanda',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='faturamentodemanda',
            name='data_aprovacao_fatura',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='faturamentodemanda',
            name='data_envio_aprovacao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='faturamentodemanda',
            name='data_fatura',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='faturamentodemanda',
            name='quantidade_horas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='faturamentodemanda',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Reprovado')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='faturamentodemanda',
            name='valor_faturamento',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='faturamentodemanda',
            name='valor_hora',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
