# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_fase'),
        ('demandas', '0004_orcamentoatividade_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeProfissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_horas', models.IntegerField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='centro_resultado',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='horas_previstas',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='responsavel',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='titulo',
        ),
        migrations.AddField(
            model_name='atividade',
            name='data_fim',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='atividade',
            name='data_inicio',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='atividade',
            name='descricao',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='atividade',
            name='fase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Fase'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='demanda',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda'),
        ),
        migrations.AddField(
            model_name='atividadeprofissional',
            name='atividade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='demandas.Atividade'),
        ),
        migrations.AddField(
            model_name='atividadeprofissional',
            name='pessoa_fisica',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.PessoaFisica'),
        ),
    ]
