# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0005_auto_20170124_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadeprofissional',
            name='horas_alocadas_milisegundos',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
