# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0005_auto_20161104_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='data_aprovacao',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='numero_proposta',
        ),
        migrations.AddField(
            model_name='demanda',
            name='codigo_cri',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='status_demanda',
            field=models.CharField(choices=[(b'O', b'Em or\xef\xbf\xbdamenta\xef\xbf\xbd\xef\xbf\xbdo'), (b'A', b'Aguardando aprova\xef\xbf\xbd\xef\xbf\xbdo'), (b'N', b'N\xef\xbf\xbdo aprovada'), (b'C', b'Cancelada'), (b'H', b'Em homologa\xef\xbf\xbd\xef\xbf\xbdo'), (b'I', b'Implantada'), (b'D', b'Em desenvolvimento')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='tipo_demanda',
            field=models.CharField(choices=[(b'D', b'Desenvolvimento'), (b'H', b'Homologa\xef\xbf\xbd\xef\xbf\xbdo'), (b'C', b'Consultoria'), (b'A', b'Aloca\xef\xbf\xbd\xef\xbf\xbdo')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='titulo',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
