# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0005_auto_20170116_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faturamentodemanda',
            name='demanda',
        ),
        migrations.RemoveField(
            model_name='valorhorafaturamento',
            name='faturamento_demanda',
        ),
        migrations.RemoveField(
            model_name='valorhorafaturamento',
            name='valor_hora',
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.PessoaFisica'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='analista_tecnico_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandas_tarefa_related', related_query_name='demandas_tarefas', to='cadastros.PessoaFisica'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.PessoaFisica'),
        ),
        migrations.DeleteModel(
            name='FaturamentoDemanda',
        ),
        migrations.DeleteModel(
            name='ValorHoraFaturamento',
        ),
    ]
