# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0006_auto_20161107_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='status_demanda',
            field=models.CharField(choices=[(b'O', b'Em or\xc3\xa7amenta\xc3\xa7\xc3\xa3o'), (b'A', b'Aguardando aprova\xc3\xa7\xc3\xa3o'), (b'N', b'N\xc3\xa3o aprovada'), (b'C', b'Cancelada'), (b'H', b'Em homologa\xc3\xa7\xc3\xa3o'), (b'I', b'Implantada'), (b'D', b'Em desenvolvimento')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='tipo_demanda',
            field=models.CharField(choices=[(b'D', b'Desenvolvimento'), (b'H', b'Homologa\xc3\xa7\xc3\xa3o'), (b'C', b'Consultoria'), (b'A', b'Aloca\xc3\xa7\xc3\xa3o')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='faturamentodemanda',
            name='valor_faturamento',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='faturamentodemanda',
            name='valor_hora',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
