# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_fase'),
        ('demandas', '0006_auto_20170117_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.PessoaJuridica'),
        ),
    ]
