# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-24 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0006_auto_20170124_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaohoras',
            name='data_informada',
            field=models.DateField(default=None),
        ),
    ]
