# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0007_auto_20161107_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recimento_solicitacao', models.DateField()),
                ('data_limite_entrega', models.DateField(null=True)),
                ('data_real_entrega', models.DateField(null=True)),
                ('numerdo_proposta', models.CharField(max_length=30, null=True)),
                ('data_aprovacao', models.DateField(null=True)),
                ('empresa_ganhadora', models.CharField(max_length=30, null=True)),
                ('total_horas_ganhadora', models.IntegerField(null=True)),
                ('demanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda')),
            ],
        ),
    ]
