# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0007_demanda_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilatividade',
            name='horas',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
