# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0007_alocacaohoras_data_informada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividadeprofissional',
            name='horas_alocadas_milisegundos',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
