# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_tipoalocacao'),
        ('demandas', '0008_auto_20170125_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaohoras',
            name='tipo_alocacao',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.TipoAlocacao'),
        ),
    ]
