# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0008_auto_20170117_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoatividade',
            name='total_horas',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
