# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0008_auto_20161031_1606'),
        ('demandas', '0008_proposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('analise_inicio', models.DateField()),
                ('analise_fim', models.DateField()),
                ('analise_fim_real', models.DateField()),
                ('densenvolvimento_inicio', models.DateField()),
                ('desenvolvimento_fim', models.DateField()),
                ('desenvolvimento_fim_real', models.DateField()),
                ('homologacao_possui_sit', models.CharField(choices=[(b'S', b'Sim'), (b'N', b'N\xc3\xa3o')], max_length=1)),
                ('homologacao_inicio', models.DateField()),
                ('homologacao_fim', models.DateField()),
                ('homologacao_fim_real', models.DateField()),
                ('forecast', models.CharField(max_length=30)),
                ('aceite', models.CharField(choices=[(b'S', b'Sim'), (b'N', b'N\xc3\xa3o')], max_length=1)),
                ('evidencias', models.CharField(max_length=30)),
                ('implantacao_producao', models.DateField()),
                ('implantacao_in_loco', models.CharField(choices=[(b'S', b'Sim'), (b'N', b'N\xc3\xa3o')], max_length=1)),
                ('analista_tecnico_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demandas_tarefa_related', related_query_name='demandas_tarefas', to='recursos.Funcionario')),
                ('demanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos.Funcionario')),
            ],
        ),
    ]
