# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-25 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0009_alocacaohoras_tipo_alocacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='percentual_concluido',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='faseatividade',
            name='percentual_concluido',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
