# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0009_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='aceite',
            field=models.CharField(choices=[(b'S', b'Sim'), (b'N', b'N\xc3\xa3o')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='analise_fim',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='analise_fim_real',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='analise_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='densenvolvimento_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='desenvolvimento_fim',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='desenvolvimento_fim_real',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='evidencias',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='forecast',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='homologacao_fim',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='homologacao_fim_real',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='homologacao_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='homologacao_possui_sit',
            field=models.CharField(choices=[(b'S', b'Sim'), (b'N', b'N\xc3\xa3o')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='implantacao_in_loco',
            field=models.CharField(choices=[(b'S', b'Sim'), (b'N', b'N\xc3\xa3o')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='implantacao_producao',
            field=models.DateField(null=True),
        ),
    ]
