# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0010_auto_20170125_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='percentual_concluido',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
