# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0011_demanda_percentual_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaohoras',
            name='hora_fim',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='alocacaohoras',
            name='hora_inicio',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
