# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0012_ocorrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_prevista_conclusao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_solicitacao',
            field=models.DateField(null=True),
        ),
    ]
