# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-30 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0013_auto_20170130_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='tipo_demanda',
            field=models.CharField(choices=[(b'E', b'Externo'), (b'I', b'Interno')], default=None, max_length=1, null=True),
        ),
    ]
