# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0013_auto_20161108_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacao',
            name='observacao',
            field=models.TextField(),
        ),
    ]
