# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20161101_1251'),
        ('demandas', '0014_auto_20161109_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoValorHoraFaturamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_hora', models.CharField(max_length=30, null=True)),
                ('quantidade_horas', models.IntegerField(null=True)),
                ('valor_faturamento', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='faturamentodemanda',
            old_name='valor_faturamento',
            new_name='valor_total_faturamento',
        ),
        migrations.RemoveField(
            model_name='faturamentodemanda',
            name='quantidade_horas',
        ),
        migrations.RemoveField(
            model_name='faturamentodemanda',
            name='tipo_hora',
        ),
        migrations.RemoveField(
            model_name='faturamentodemanda',
            name='valor_hora',
        ),
        migrations.AddField(
            model_name='tipovalorhorafaturamento',
            name='faturamento_demanda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.FaturamentoDemanda'),
        ),
        migrations.AddField(
            model_name='tipovalorhorafaturamento',
            name='tipo_hora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.TipoValorHora'),
        ),
    ]
