# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0014_auto_20170130_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='data_criacao',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='status_demanda',
            field=models.CharField(choices=[('O', 'Em orçamentação'), ('A', 'Aguardando aprovação'), ('N', 'Não aprovada'), ('C', 'Cancelada'), ('H', 'Em homologação'), ('I', 'Implantada'), ('D', 'Em desenvolvimento')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='tipo_demanda',
            field=models.CharField(choices=[('E', 'Externo'), ('I', 'Interno')], default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='etapa',
            field=models.CharField(choices=[('C', 'Concluído'), ('A', 'Aguardando análise'), ('E', 'Em avaliação')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='tipo_ocorrencia',
            field=models.CharField(choices=[('E', 'Erro'), ('S', 'Erro de Especificação'), ('F', 'Fora do escopo inicial do projeto')], max_length=1),
        ),
    ]
