# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-02 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0015_auto_20170201_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='data_fim',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='data_inicio',
            field=models.DateField(default=None, null=True),
        ),
    ]
