# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0015_auto_20161110_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturamentodemanda',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
