# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0016_auto_20161110_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='data_aprovacao_demanda',
            field=models.DateField(default=None),
        ),
    ]
