# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0018_despesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='a_faturar',
            field=models.NullBooleanField(default=None),
        ),
    ]
