# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0019_auto_20161115_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faturamentodemanda',
            name='data',
        ),
        migrations.RemoveField(
            model_name='faturamentodemanda',
            name='data_aprovacao_fatura',
        ),
        migrations.AddField(
            model_name='faturamentodemanda',
            name='data_pagamento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='faturamentodemanda',
            name='data_previsto_faturamento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='faturamentodemanda',
            name='data_previsto_pagamento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='faturamentodemanda',
            name='numero_nota',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
