# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0019_auto_20170207_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='imposto_devidos',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='total_despesas',
            field=models.FloatField(default=None, null=True),
        ),
    ]
