# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_auto_20170203_1153'),
        ('demandas', '0020_auto_20170208_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='valor_hora_orcamento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.ValorHora'),
        ),
    ]
