# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0021_auto_20161121_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='valor_total',
            field=models.FloatField(default=None),
        ),
    ]
