# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0021_orcamento_valor_hora_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='valor_desejado',
            field=models.FloatField(default=None, null=True),
        ),
    ]
