# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0022_fase_valor_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='descricao',
            field=models.TextField(default=None, null=True),
        ),
    ]
