# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0008_auto_20161031_1606'),
        ('clientes', '0005_auto_20161116_0954'),
        ('demandas', '0023_auto_20161121_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=10)),
                ('horas_previstas', models.IntegerField()),
                ('centro_resultado', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='clientes.CentroResultado')),
            ],
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='centro_resultado',
        ),
        migrations.AddField(
            model_name='atividade',
            name='demanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandas.Demanda'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='responsavel',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recursos.Funcionario'),
        ),
    ]
