# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0023_orcamento_horas_desejado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='lucro_calculado_desejado',
            field=models.FloatField(default=None, null=True),
        ),
    ]
