# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0024_orcamento_lucro_calculado_desejado'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='horas_projetadas',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_projetado',
            field=models.FloatField(default=None, null=True),
        ),
    ]
