# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0024_auto_20161122_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='centro_resultado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.CentroResultado'),
        ),
    ]
