# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0025_auto_20170208_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='lucro_calculado_projetado',
            field=models.FloatField(default=None, null=True),
        ),
    ]
