# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0025_auto_20161122_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
