# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_valorhora_vigencia'),
        ('demandas', '0026_auto_20161122_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorHoraFaturamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('quantidade_horas', models.IntegerField(null=True)),
                ('valor_faturamento', models.CharField(max_length=30, null=True)),
                ('faturamento_demanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demandas.FaturamentoDemanda')),
                ('valor_hora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.ValorHora')),
            ],
        ),
        migrations.RemoveField(
            model_name='tipovalorhorafaturamento',
            name='faturamento_demanda',
        ),
        migrations.RemoveField(
            model_name='tipovalorhorafaturamento',
            name='tipo_hora',
        ),
        migrations.DeleteModel(
            name='TipoValorHoraFaturamento',
        ),
    ]
