# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0027_auto_20161123_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorhorafaturamento',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
