# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_auto_20170203_1153'),
        ('demandas', '0027_auto_20170208_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemfase',
            old_name='fase',
            new_name='orcamento_fase',
        ),
        migrations.RemoveField(
            model_name='orcamentofase',
            name='descricao',
        ),
        migrations.AddField(
            model_name='orcamentofase',
            name='fase',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Fase'),
        ),
    ]
