# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-08 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0028_auto_20170208_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentofase',
            name='dias',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
