# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0028_auto_20161123_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='centro_custo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.CentroCusto'),
        ),
    ]
