# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0029_auto_20161129_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='total_orcamento',
            field=models.FloatField(default=None, null=True),
        ),
    ]
