# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0029_orcamentofase_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='nome_demanda',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
