# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0030_auto_20170213_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faseatividade',
            name='fase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='cadastros.Fase'),
        ),
        migrations.AlterField(
            model_name='orcamentoatividade',
            name='fase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Fase'),
        ),
        migrations.AlterField(
            model_name='orcamentofase',
            name='fase',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.Fase'),
        ),
    ]
