# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0030_auto_20161129_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='codigo_cri',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='identificacao',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='tipo_demanda',
        ),
        migrations.RemoveField(
            model_name='demanda',
            name='titulo',
        ),
        migrations.AddField(
            model_name='demanda',
            name='codigo_demanda',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='nome_demanda',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
