# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0031_auto_20161129_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='data_aprovacao_demanda',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='demanda',
            name='descricao',
            field=models.TextField(default=None, null=True),
        ),
    ]
