# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0031_auto_20170215_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfase',
            name='quantidade_horas',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
