# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0032_auto_20161129_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='data_aprovacao_demanda',
        ),
    ]
