# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0033_remove_demanda_data_aprovacao_demanda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='centro_custo',
        ),
    ]
