# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0033_remove_demanda_analista_tecnico_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfase',
            name='quantidade_horas',
            field=models.FloatField(default=None, null=True),
        ),
    ]
