# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0034_auto_20170215_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='codigo_demanda',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
