# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0036_auto_20161129_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demanda',
            name='unidade_administrativa',
        ),
    ]
