# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0036_demanda_recorrente'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='forma_pagamento',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='demanda',
            name='particularidade_proposta',
            field=models.TextField(default=None, null=True),
        ),
    ]
