# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0038_demanda_unidade_administrativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='tipo_parcela',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
