# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0039_auto_20170308_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='status_demanda',
            field=models.CharField(choices=[('O', 'Em orçamentação'), ('A', 'Aguardando aprovação'), ('N', 'Não aprovada'), ('C', 'Cancelada'), ('H', 'Em homologação'), ('I', 'Implantada'), ('D', 'Em desenvolvimento'), ('E', 'Deletado')], max_length=1, null=True),
        ),
    ]
