# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-05 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0039_demanda_tipo_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='tipo_parcela',
            field=models.CharField(choices=[(b'P', b'Parcela'), (b'M', b'Medi\xc3\xa7\xc3\xa3o')], max_length=1, null=True),
        ),
    ]
