# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0040_auto_20170330_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='demanda',
            name='data_finalizacao',
            field=models.DateField(default=None),
        ),
    ]
