# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0041_demanda_data_finalizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='data_finalizacao',
            field=models.DateField(default=None, null=True),
        ),
    ]
