# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0042_auto_20170921_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='data_conclusao_atividade',
            field=models.DateField(default=None, null=True),
        ),
    ]
