# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messagem',
            new_name='Mensagem',
        ),
    ]
