# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0002_auto_20170328_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensagem',
            old_name='pessoa',
            new_name='pessoa_fisica',
        ),
        migrations.RenameField(
            model_name='responsavel',
            old_name='pessoa',
            new_name='pessoa_fisica',
        ),
    ]
