# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0003_auto_20170328_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='data_criacao',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='tag',
            field=models.CharField(choices=[('E', 'Exame Periodico'), ('A', 'Alocacao de horas'), ('N', 'Aniversarios')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='tag',
            field=models.CharField(choices=[('E', 'Exame Periodico'), ('A', 'Alocacao de horas'), ('N', 'Aniversarios')], default=None, max_length=1),
        ),
    ]
