# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0004_auto_20170328_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='origem',
            field=models.CharField(default='SISTEMA', max_length=30, null=True),
        ),
    ]
