# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0005_mensagem_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='tag',
            field=models.CharField(choices=[('E', 'Exame Periodico'), ('A', 'Alocacao de horas'), ('N', 'Aniversarios'), ('D', 'Nao lancamento dois dias'), ('F', 'Fim de fase'), ('R', 'Renegociacao'), ('P', 'Propostas pendentes'), ('G', 'Pagamento de nota')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='responsavel',
            name='tag',
            field=models.CharField(choices=[('E', 'Exame Periodico'), ('A', 'Alocacao de horas'), ('N', 'Aniversarios'), ('D', 'Nao lancamento dois dias'), ('F', 'Fim de fase'), ('R', 'Renegociacao'), ('P', 'Propostas pendentes'), ('G', 'Pagamento de nota')], default=None, max_length=1),
        ),
    ]
