# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-30 12:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos', '0002_auto_20161227_1058'),
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao_social', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('C', 'CLIENTE'), ('F', 'FORNECEDOR'), ('A', 'AMBOS')], max_length=1)),
                ('tipo_pessoa', models.CharField(choices=[('F', 'FISICA'), ('J', 'JURIDICA')], max_length=1)),
                ('data_contratacao', models.DateField()),
                ('data_rescisao', models.DateField(default=None, null=True)),
                ('data_fim_aditivo', models.DateField(default=None, null=True)),
                ('data_renegociacao_valor', models.DateField(default=None, null=True)),
                ('dias_faturamento', models.IntegerField(default=None, null=True)),
                ('dias_pagamento', models.IntegerField(default=None, null=True)),
                ('status', models.BooleanField()),
                ('centro_custo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.CentroCusto')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default=None, max_length=30)),
                ('email', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosBancariosPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conta', models.CharField(choices=[('S', 'CONTA SALARIO'), ('C', 'CONTA CORRENTE'), ('P', 'CONTA POUPANCA')], default=None, max_length=1)),
                ('nome_banco', models.CharField(default=None, max_length=20)),
                ('cod_banco', models.CharField(max_length=4)),
                ('cod_agencia', models.CharField(default=None, max_length=10)),
                ('num_conta', models.CharField(default=None, max_length=10)),
                ('pessoa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.CadastroPessoa')),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=10)),
                ('pessoa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.CadastroPessoa')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(default=None, max_length=16)),
                ('rg', models.CharField(default=None, max_length=16)),
                ('orgao_emissor', models.CharField(max_length=6)),
                ('data_expedicao', models.DateField()),
                ('email', models.CharField(default=None, max_length=50, null=True)),
                ('data_nascimento', models.DateField()),
                ('estado_civil', models.CharField(choices=[('C', 'CASADO'), ('S', 'SOLTEIRO'), ('D', 'DIVORCIADO')], default=None, max_length=1)),
                ('naturalidade', models.CharField(default=None, max_length=30)),
                ('nacionalidade', models.CharField(default=None, max_length=30)),
                ('sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=1)),
                ('grau_instrucao', models.CharField(choices=[('1G', '1GRAU'), ('2G', '2GRAU'), ('GR', 'GRADUADO'), ('PO', 'POS-GRADUADO'), ('DO', 'DOUTURADO'), ('ME', 'MESTRADO')], default=None, max_length=2)),
                ('nome_pai', models.CharField(default=None, max_length=30)),
                ('nome_mae', models.CharField(default=None, max_length=30)),
                ('deficiencia', models.CharField(choices=[('F', 'FISICA'), ('A', 'AUDITIVA'), ('V', 'VISUAL'), ('I', 'INTELECTUAL'), ('M', 'MENTAL'), ('R', 'REABILITADO')], default=None, max_length=1)),
                ('num_pis', models.CharField(default=None, max_length=30)),
                ('data_emicao_pis', models.DateField()),
                ('num_titulo_eleitoral', models.CharField(default=None, max_length=30)),
                ('zona', models.CharField(default=None, max_length=4)),
                ('secao', models.CharField(default=None, max_length=4)),
                ('doc_militar', models.CharField(default=None, max_length=30)),
                ('categoria_doc_militar', models.CharField(default=None, max_length=10)),
                ('pessoa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.CadastroPessoa')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(default=None, max_length=19)),
                ('nome_fantasia', models.CharField(default=None, max_length=30)),
                ('inscricao_estadual', models.CharField(default=None, max_length=20)),
                ('inscricao_municipal', models.CharField(default=None, max_length=20)),
                ('pessoa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.CadastroPessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prestador', models.CharField(choices=[('S', 'SOCIO'), ('A', 'AUTONOMO'), ('F', 'FUNCIONARIO'), ('P', 'PJ')], max_length=1)),
                ('data_exame_admissional', models.DateField(default=None)),
                ('data_exame_demissional', models.DateField(default=None, null=True)),
                ('data_ultimo_exame_periodico', models.DateField(default=None, null=True)),
                ('dataa_ultima_avaliacao', models.DateField(default=None, null=True)),
                ('data_proxima_avaliacao', models.DateField(default=None, null=True)),
                ('dados_complementares', models.TextField(default=None, null=True)),
                ('cargo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='recursos.Cargo')),
                ('pessoa_fisica', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.PessoaFisica')),
                ('usuario', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TelefoneContato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('R', 'RESIDENCIAL'), ('C', 'COMERCIAL'), ('M', 'CELULAR')], default=None, max_length=1)),
                ('numero', models.CharField(max_length=20)),
                ('contato', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Contato')),
            ],
        ),
        migrations.CreateModel(
            name='TelefonePessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('R', 'RESIDENCIAL'), ('C', 'COMERCIAL'), ('M', 'CELULAR')], default=None, max_length=1)),
                ('numero', models.CharField(max_length=20)),
                ('pessoa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.CadastroPessoa')),
            ],
        ),
        migrations.AddField(
            model_name='contato',
            name='pessoa_juridica',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.PessoaJuridica'),
        ),
    ]
