# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20161230_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao_social', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('C', 'CLIENTE'), ('F', 'FORNECEDOR'), ('A', 'AMBOS')], max_length=1)),
                ('tipo_pessoa', models.CharField(choices=[('F', 'FISICA'), ('J', 'JURIDICA')], max_length=1)),
                ('data_contratacao', models.DateField()),
                ('data_rescisao', models.DateField(default=None, null=True)),
                ('data_fim_aditivo', models.DateField(default=None, null=True)),
                ('data_renegociacao_valor', models.DateField(default=None, null=True)),
                ('dias_faturamento', models.IntegerField(default=None, null=True)),
                ('dias_pagamento', models.IntegerField(default=None, null=True)),
                ('status', models.CharField(default=None, max_length=1, null=True)),
                ('centro_custo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.CentroCusto')),
            ],
        ),
        migrations.RemoveField(
            model_name='cadastropessoa',
            name='centro_custo',
        ),
        migrations.AddField(
            model_name='enderecopessoa',
            name='tipo',
            field=models.CharField(choices=[('RE', 'RESIDENCIAL'), ('CO', 'COMERCIAL'), ('CB', 'COBRANCA'), ('EN', 'ENTREGA')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='dadosbancariospessoa',
            name='pessoa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Pessoa'),
        ),
        migrations.AlterField(
            model_name='enderecopessoa',
            name='pessoa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='num_pis',
            field=models.CharField(default=None, max_length=14),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='pessoa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='pessoa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Pessoa'),
        ),
        migrations.AlterField(
            model_name='telefonepessoa',
            name='pessoa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Pessoa'),
        ),
        migrations.DeleteModel(
            name='CadastroPessoa',
        ),
    ]
