# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_centroresultado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaGerencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
    ]
