# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20170102_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='nome_pai',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
