# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20170102_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='deficiencia',
            field=models.CharField(choices=[('F', 'FISICA'), ('A', 'AUDITIVA'), ('V', 'VISUAL'), ('I', 'INTELECTUAL'), ('M', 'MENTAL'), ('R', 'REABILITADO')], default=None, max_length=1, null=True),
        ),
    ]
