# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_auto_20170102_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='cargo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos.Cargo'),
        ),
    ]
