# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-03 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_auto_20170103_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='data_exame_admissional',
            field=models.DateField(default=None, null=True),
        ),
    ]
