# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_auto_20170103_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_contratacao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='nome_fantasia',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
