# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_auto_20170104_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoajuridica',
            name='inscricao_estadual',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
