# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_auto_20170105_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apropriacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_custo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.CentroCusto')),
                ('centro_resultado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.CentroResultado')),
                ('conta_gerencial', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.ContaGerencial')),
                ('natureza_operacao', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.NaturezaOperacao')),
                ('pessoa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Pessoa')),
                ('unidade_administrativa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.UnidadeAdministrativa')),
            ],
        ),
    ]
