# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_apropriacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustoPrestador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(default=None)),
                ('data_fim', models.DateField(default=None, null=True)),
                ('valor', models.FloatField(default=None, max_length=30)),
                ('pessoa_fisica', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cadastros.PessoaFisica')),
            ],
        ),
    ]
