# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_custoprestador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='centro_custo',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='data_contratacao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='data_fim_aditivo',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='data_rescisao',
        ),
        migrations.AddField(
            model_name='prestador',
            name='data_contratacao',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='data_fim_aditivo',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='prestador',
            name='data_rescisao',
            field=models.DateField(default=None, null=True),
        ),
    ]
