# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0015_auto_20170105_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestador',
            name='pessoa_juridica',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.PessoaJuridica'),
        ),
    ]
