# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-02 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_tipoalocacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='enderecopessoa',
            name='bairro',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='deficiencia',
            field=models.CharField(choices=[('N', 'NAO'), ('F', 'FISICA'), ('A', 'AUDITIVA'), ('V', 'VISUAL'), ('I', 'INTELECTUAL'), ('M', 'MENTAL'), ('R', 'REABILITADO')], default=None, max_length=1, null=True),
        ),
    ]
