# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_fase_centro_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadeadministrativa',
            name='custo_operacao_hora',
            field=models.FloatField(default=None, null=True),
        ),
    ]
