# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0024_unidadeadministrativa_custo_operacao_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoafisica',
            name='unidade_administrativas',
            field=models.ManyToManyField(default=None, null=True, to='cadastros.UnidadeAdministrativa'),
        ),
    ]
