# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0026_auto_20170224_1130'),
        ('cadastros', '0025_auto_20170303_1025'),
    ]

    operations = [
    ]
