# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0027_merge_20170307_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoajuridica',
            name='forma_pagamento',
            field=models.TextField(default=None, null=True),
        ),
    ]
