# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0029_pessoajuridica_particularidade_proposta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=300)),
                ('content_type', models.CharField(max_length=300)),
                ('tamanho', models.BigIntegerField()),
                ('path_arquivo', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='pessoajuridica',
            name='arquivo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Arquivo'),
        ),
    ]
