# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(default=None, max_length=11)),
                ('rg', models.CharField(default=None, max_length=10)),
                ('endereco', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('cep', models.CharField(max_length=10)),
                ('salario', models.CharField(max_length=20)),
                ('data_admissao', models.DateField(blank=True, default=None)),
                ('cargo', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='recursos.Cargo')),
            ],
        ),
    ]
