# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default=None, max_length=16),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(default=None, max_length=16),
        ),
    ]
