# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default=None, max_length=11),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='rg',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
