# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_auto_20161227_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.AddField(
            model_name='cargo',
            name='gestor',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
