# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_funcionario_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='data_admissao',
        ),
    ]
