# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0004_remove_funcionario_data_admissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='recursos.Cargo'),
        ),
    ]
