# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0005_auto_20161031_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.CharField(max_length=20),
        ),
    ]
