# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0006_auto_20161031_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(default=None),
        ),
    ]
