# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0007_funcionario_data_admissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(blank=True, default=None),
        ),
    ]
